apiVersion: apps/v1
kind: Deployment
metadata:
  name: q6-app
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: q6-app
  template:
    metadata:
      labels:
        app: q6-app
    spec:
      containers:
      - name: q6-app
        image: nessa91/qn2:latest
        ports:
        - containerPort: 8080
