apiVersion: v1
kind: Service
metadata:
  name:  q6-app
  labels:
    app:  q6-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30038
    targetPort: 80
    protocol: TCP
  selector:
    app:  q6-app

